server:
  host: 0.0.0.0
  port: 8884
  use_ngrok: false
  use_auth: false
  auth_username: user
  auth_password: password
  log_file_path: logs\tts_server.log
  log_file_max_size_mb: 10
  log_file_backup_count: 5
model:
  repo_id: chatterbox-turbo
tts_engine:
  device: cuda
  predefined_voices_path: voices
  reference_audio_path: reference_audio
  default_voice_id: Emily.wav
paths:
  model_cache: models
  output: outputs
generation_defaults:
  temperature: 0.8
  exaggeration: 1.3
  cfg_weight: 0.5
  seed: 4
  speed_factor: 1
  language: en
text_processing:
  split_text_enabled: true
  chunk_size: 240
audio_output:
  format: mp3
  sample_rate: 24000
  max_reference_duration_sec: 30
  save_to_disk: false
ui_state:
  last_text: "[gasp] This is a disaster! An absolute catastrophe! [groan] The souffl\xE9\
    \ has fallen, and with it, my will to live! [sigh] Twenty years I have trained\
    \ for this moment, and the universe conspires against me!\n"
  last_voice_mode: predefined
  last_predefined_voice: af_miniko.wav
  last_reference_file: nyan.wav
  last_seed: 5
  last_chunk_size: 240
  last_split_text_enabled: true
  hide_chunk_warning: false
  hide_generation_warning: true
  theme: dark
  last_preset_name: "\u26A1 Turbo: The Overly Dramatic Chef"
ui:
  title: Chatterbox TTS Server
  show_language_select: true
  max_predefined_voices_in_dropdown: 50
debug:
  save_intermediate_audio: false
